<a href="https://colab.research.google.com/github/sarahethompson/eportfolio/blob/main/artefacts/module-3/unit-7-perceptron-and-operator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Author: Dr Mike Lakoju, CardiffMet

### Import Library

In [1]:
import numpy as np

### Define "Inputs, outputs and weights" as Numpy arrays

#### Inputs

In [2]:
# Creating input values as a matrix not as a vector
inputs = np.array([[0,0], [0,1], [1,0], [1,1]])

In [5]:
# Chcking the shape of the inputs

inputs.shape

(4, 2)

**The output (4, 2) means the array has 4 rows and 2 columns.**

#### Outputs

In [3]:
outputs = np.array([0, 0, 0, 1])

In [4]:
#Checking the shape of the outputs

outputs.shape

(4,)

**The output (4,) indicates that the array is a one-dimensional array with 4 elements.**

#### Weights

In [6]:
# one weight for x1 and one for x2
weights = np.array([0.0, 0.0])

#### Learning Rate

In [7]:
learning_rate = 0.1

## Step function

In [8]:
# This is our Activation function

def step_function(sum):
  if (sum >= 1):
    #print(f'The Sum of Weights is Greater or equal to 1')
    return 1
  else:
        #print(f'The Sum of Weights is NOT > or = to 1')
        return 0

**This code defines a step_function which serves as the activation function for the neural network. It takes a single argument sum. If sum is greater than or equal to 1, the function returns 1; otherwise, it returns 0. This type of function is often used in simple perceptrons to produce a binary output (0 or 1).**

## Process Output

<b>We define a function that allows us to calculate/ process the output. The function accepts an instance of our data, then calculate the sum function using Numpy. Finally, we check the output by passing it through the "Step Function."</b>

In [9]:
def cal_output(instance):
  sum_func = instance.dot(weights)
  return step_function(sum_func)

We pass it as alist in a numpy array ...

In [10]:
cal_output(np.array([[1,1]]))

0

## Train

In [11]:
# Check the number of outputs

len(outputs)

4

In [12]:
# Checking the index of the input at postion 3 ..
# this is the last inpute value
inputs[3]

array([1, 1])

In [14]:
inputs

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

<b>Note that:</b> usually, we will need to define the number of epochs, because we will never really get a value of zero when dealing with real-world data. However, for this small data, we will run the loop till we obtain zero error

In [29]:
def train():
    #
    total_error_value = 1
    # While the total_error_value is not equal to zero. we are asumming that at the start of running our network there will be no zero
    while (total_error_value != 0):
        #making the total_error 0 so we can do other calculations
        total_error_value = 0
        #Looping into each row of the dataset (remember indexing in python starts at zero hence 0-3 which are 4 values)
        for i in range(len(outputs)):
            #Calculating predictions
            prediction = cal_output(inputs[i])
            # Calculating the absolute value of the error
            error = abs(outputs[i] - prediction)
            #Updating the error
            total_error_value  += error

            if error > 0:
                for j in range(len(weights)):
                    #updating the weights for x1 and x2
                    weights[j] = weights[j] + (learning_rate * inputs[i][j] * error)
                    print('Weight updated to: ' + str(weights[j]))
        print('Total error Value: ' + str(total_error_value))

**This code defines the train function, which implements the training process for the perceptron. It uses a while loop that continues as long as total_error_value is not zero. Inside the loop, it iterates through each input-output pair, calculates the prediction using cal_output, and determines the error. If there's an error, it updates the weights based on the learning_rate, input value, and error. The total_error_value is updated in each iteration, and the process stops when the total error is 0.**

In [34]:
train()

Total error Value: 0


## Classification

In [28]:
# Now we have the final weights that will be used to classify new instances of the data after training.

weights

array([0.5, 0.5])

In [35]:
cal_output(np.array([0,0]))

0

In [36]:
cal_output(np.array([0,1]))

0

In [37]:
cal_output(np.array([1,0]))

0

In [38]:
cal_output(np.array([1,1]))

1